spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineteach?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Nham3112@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  expiryTime: 3600000
  secretKey: Vx9ncuYCx5CKZahynDpvSnD06d7ym5qVfGUwHnWdjak=
  refreshKey: 8bmgOu8iLdUid9x3ZmN+zAFzDDKuEDdr+N0FGQ656cA=